_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 49
                - 55
            "2":
                - 1
                - 2
                - 3
                - 49
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
ball_sizes:
    value:
        - 256
        - 256
        - 256
        - 256
batch_size:
    value: 8
data_path:
    value: ./data/cosmology
dec_depths:
    value:
        - 2
        - 2
        - 2
dec_num_heads:
    value:
        - 2
        - 4
        - 8
enc_depths:
    value:
        - 2
        - 2
        - 6
        - 2
enc_num_heads:
    value:
        - 2
        - 4
        - 8
        - 16
experiment:
    value: glx_node
lr:
    value: 0.0005
model:
    value: erwin
mp_steps:
    value: 0
mv_dim_in:
    value: 32
mv_dims:
    value:
        - 32
        - 64
        - 128
        - 256
num_epochs:
    value: 3000
num_parameters:
    value: 99828525
num_samples:
    value: 8192
rotate:
    value: 0
s_dims:
    value:
        - 32
        - 64
        - 128
        - 256
seed:
    value: 0
size:
    value: small
strides:
    value:
        - 2
        - 2
        - 2
test:
    value: true
use_wandb:
    value: true
val_every_iter:
    value: 500
