_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
base_channels:
    value: 32
batch_size:
    value: 4
data_path:
    value: /home/aema/Desktop/erwin-main/data/cosmology
depths:
    value:
        - 2
        - 2
        - 2
experiment:
    value: glx_node
in_channels:
    value: 1
lr:
    value: 0.0005
model:
    value: equi_erwin
num_epochs:
    value: 10
num_heads:
    value: 4
num_parameters:
    value: 171971
num_samples:
    value: 128
seed:
    value: 0
size:
    value: small
test:
    value: true
use_wandb:
    value: true
val_every_iter:
    value: 10
