_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 49
                - 55
            "2":
                - 1
                - 2
                - 3
                - 49
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
auxiliarympnn:
    value: false
ball_sizes:
    value:
        - 128
        - 128
        - 128
batch_size:
    value: 8
c_hidden:
    value:
        - 8
        - 16
        - 32
c_in:
    value: 8
data_path:
    value: ./data/cosmology
dec_depths:
    value:
        - 2
        - 2
dec_num_heads:
    value:
        - 2
        - 4
embedt:
    value: false
enc_depths:
    value:
        - 2
        - 2
        - 6
enc_num_heads:
    value:
        - 2
        - 4
        - 8
experiment:
    value: base_smaller_MPNN_RotatingTree
lr:
    value: 0.0005
model:
    value: erwin
mp_steps:
    value: 3
mpsteps:
    value: 3
num_epochs:
    value: 5000
num_parameters:
    value: 128891
num_samples:
    value: 8192
rotate:
    value: 90
seed:
    value: 1
size:
    value: smaller
strides:
    value:
        - 2
        - 2
test:
    value: true
use_wandb:
    value: true
val_every_iter:
    value: 500
